### ISSUE TITLE
List of changes

### ISSUE THREAD

**Issue by DeathDragon7050** [maletsna/xSE#1]
This mod used to be on Nexus Mods but now isn't. Your readme contains basically no info on what the mod does. What does this mod even do?

**Comment by Tearlow** [comment]
While I agree that some things should be explained better I'd have to also point out that the source code is available here.

https://github.com/maletsna/xSE/blob/c81a3d630cda1db055858f6fe6fb06e63549cc0b/unnecessary_tweaks/main.cpp#L50

This is where the entries for the ini file start which gives you a better idea. Hopefully that help answers some of your questions...

**Comment by DeathDragon7050** [comment]
I see thanks. Although you should get around to compiling a list of changes for other people.

**Comment by Tearlow** [comment]
I think you confuse me with @maletsna I am but a user in this case *Chuckles*

**Comment by DeathDragon7050** [comment]
Oops haha sorry.
